name: pocket-js-server

services:
  pg:
    image: bitnami/postgresql:13.16.0
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=inorbit

  server:
    build: .
    volumes:
      - .:/app
    ports:
      - '3333:3333'
    depends_on:
      - pg
    environment:
      DATABASE_URL: postgresql://docker:docker@pg:5432/inorbit
    command: sh -c "npm install && npm run migrate && npm run dev"